### ISSUE TITLE
data not as aspected

### ISSUE THREAD

**Issue by Mediacj** [rickvanderzwet/GrowattReader#1]
Thanks for sharing this script!

I tried it with mine Growatt 1500S but the data is not as expected:
energy_today;energy_total;grid_freq;grid_voltage;inverter_fault;inverter_status;output_power;pv1_vol
tage;pv2_voltage;raw;temperature;time;total_time_worked
5196.7;82379916.3;653.25;6550.9;51;253;6000.7;6209.1;6550.9;V/KL++X/5f/l/y3qZ/99/TP55SX5yv8xGi17KXstew==;6540.5;1530553556.229258;69593842.7

The numbers don't reflect the real situation.  What is the dipswitch setting on your RS232 port?

I use a USB to serial cable with a raspberry pi with raspbian.

Any idea what could be wrong? Thx in advance!

**Comment by rixvet** [comment]
Good question. I do not have a Growatt variant with DIP switch, so I have to guess... The DIP switch settings in the WiFi manual of the  dongle mentions setting DIP switch (if present) to values `1=on and 2=off`. 

I am also using a raspberry Pi with Raspbian and had to use a powered hub and/or an alternative USB serial dongle, some of them garbled my output. 

I have also just uploaded the manual for the serial communication, allowing to decode the raw information yourself as well. I would be happy to take a look at your `raw` values how-ever I need more lines off output to be able to find out what is causing this confusion, could you run the script for a while (1 hour) and post it here?

Could you also output some known values like grid frequency/voltage (range), allowing me to back-trace the raw output to real values.

**Comment by Mediacj** [comment]
Thanx for your response!
 
I have tried any dip switch combination but the result stays the same so I think it's not directly related, the powered hub could indeed be a solution cause the data seems garbled. 

I'll try it tomorrow and let you now together with more data if it's not the power.

**Comment by Mediacj** [comment]
Unfortunately the powered usb didn't change the output.

Mine inverter is the Growatt 2500MTL-S
I have 8 pv panels 275WP each connected in two strings (each 4)

I have collected some raw data(see attached output.txt) maybe you can see if it is usable or whatever:
The values today when I was collecting the data where:
ETODAY: 13.0 kWh
EALL: 186.9kWh
Ppv: 23/ 55W 
69.9VA 68.4W
PV: 82/124 B:360
AC:235V F:50,0Hz

Many thanks again!

[output.txt](https://github.com/rickvanderzwet/GrowattReader/files/2164123/output.txt)

**Comment by Mediacj** [comment]
I just received a newer version of the serial communication manual from Growatt which should apply to my inverter, see attached pdf.

Thx!

[Growatt PV Inverter Modbus RS485 RTU Protocol V3 14.pdf](https://github.com/rickvanderzwet/GrowattReader/files/2164157/Growatt.PV.Inverter.Modbus.RS485.RTU.Protocol.V3.14.pdf)

**Comment by rixvet** [comment]
This explains the confusion. You are using a **MTL-S** series inverters, those have a very different way of accessing the data from the **S** series. You could try to use [a modbus client example](https://fixedbycode.blogspot.com/2014/04/how-to-upload-data-from-growatt.html) to find out whether this work for your case.

I unfortunately do not have the hardware available to be able to make the script compatible/workable with your version of the hardware. I will update the documentation to ensure this is properly mentioned.

**Comment by Mediacj** [comment]
Ok I understand, many thanks for your time!

**Comment by Mediacj** [comment]
Hij heeft al gereageerd.....en aangegeven dat een andere import wellicht
beter werkt....

Op wo 4 jul. 2018 om 21:27 schreef Rick van der Zwet <
notifications@github.com>:
